services:
  app:
    build:
      target: app-interactive
      args:
        LANG: "${LANG:-en_US.UTF-8}"
        TZ:
        UNMINIMIZE: true
        GIT_USER:
        GIT_EMAIL:
        GIT_DEFAULT_BRANCH: "master"
        GIT_INSTALL_GCM: false
    environment:
      HOST_UID: 1000
      HOST_GID: 1000
      TERM: "${TERM}"
      ZSH_THEME: "powerlevel10k/powerlevel10k"
    volumes:
      # Source
      - ".:/app"
      # Credentials
      - "~/.config/composer/auth.json:/home/exterminate/.config/composer/auth.json"
      # VS Code server
      - "vscode:/home/exterminate/.vscode-server"

volumes:
  vscode:
    driver: local
